package br.edu.infnet.projeto_bloco_micro_servicos.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "tv_show_history")
public class TVShowHistory {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "tv_show_id")
    private int tvShowId;

    private String title;
    private String genre;
    private int season;
    private int episode;

    private LocalDateTime timestamp;
    private String action;

    // Constructors, getters, and setters are automatically generated by Lombok

}

